package fr.minenorth.drill.job;
import fr.minenorth.drill.config.SystemeConfigFiles;
import java.io.IOException; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.util.*;
public final class JobConfig {
 public static final class Job { public String id="",name="",description="",permission="",icon="minecraft:paper",selectCommand="",leaveCommand=""; public int max=0,salary=0; public boolean premium=false,candidature=false,clearInventoryOnSelect=false,clearInventoryOnLeave=false; }
 private static final List<Job> JOBS=new ArrayList<>(); private static boolean enabled=true,salaryEnabled=false; private static int interval=40; private static String salaryCommand="",assignCommand="",defaultJob="civil",premiumPermission="premium.job";
 public static synchronized void load(){ SystemeConfigFiles.init(); Path p=SystemeConfigFiles.getRoot().resolve("emplois.toml"); try{if(!Files.exists(p))writeDefault(p); List<String> ls=Files.readAllLines(p,StandardCharsets.UTF_8); JOBS.clear(); Job cur=null; String sec=""; for(String raw:ls){String l=raw.trim(); if(l.isEmpty()||l.startsWith("#"))continue; if(l.equals("[[jobs]]")){cur=new Job();JOBS.add(cur);sec="jobs";continue;} if(l.equals("[general]")){cur=null;sec="general";continue;} if(l.equals("[salary]")){cur=null;sec="salary";continue;} int e=l.indexOf('=');if(e<0)continue;String k=l.substring(0,e).trim(),v=l.substring(e+1).trim(); if(cur!=null)set(cur,k,v); else if(sec.equals("general")){if(k.equals("enabled"))enabled=bool(v,true);else if(k.equals("default_job"))defaultJob=str(v,"civil");else if(k.equals("assign_command"))assignCommand=str(v,"");else if(k.equals("premium_permission"))premiumPermission=str(v,"premium.job");}else if(sec.equals("salary")){if(k.equals("enabled"))salaryEnabled=bool(v,false);else if(k.equals("interval_minutes"))interval=Math.max(1,num(v,40));else if(k.equals("command"))salaryCommand=str(v,"");}}}catch(Exception ignored){} if(JOBS.isEmpty())defaults(); if(byId(defaultJob)==null&&!JOBS.isEmpty())defaultJob=JOBS.get(0).id; }
 private static void set(Job j,String k,String v){switch(k){case"id"->j.id=str(v,"");case"name"->j.name=str(v,"");case"description"->j.description=str(v,"");case"max"->j.max=Math.max(0,num(v,0));case"salary"->j.salary=Math.max(0,num(v,0));case"premium"->j.premium=bool(v,false);case"candidature"->j.candidature=bool(v,false);case"permission"->j.permission=str(v,"");case"icon"->j.icon=str(v,"minecraft:paper");case"select_command"->j.selectCommand=str(v,"");case"leave_command"->j.leaveCommand=str(v,"");case"clear_inventory_on_select"->j.clearInventoryOnSelect=bool(v,false);case"clear_inventory_on_leave"->j.clearInventoryOnLeave=bool(v,false);}}
 private static String str(String s,String d){return s.startsWith("\"")&&s.endsWith("\"")?s.substring(1,s.length()-1).replace("\\\"","\""):d;} private static int num(String s,int d){try{return Integer.parseInt(s.trim());}catch(Exception e){return d;}} private static boolean bool(String s,boolean d){return s.equalsIgnoreCase("true")?true:s.equalsIgnoreCase("false")?false:d;}
 private static void defaults(){String[][] a={{"civil","Civil","Vivez votre vie et développez vos activités.","0","0","false","false"},{"taxi","Taxi","Emmenez vos clients à leurs destinations.","0","0","false","false"},{"avocat","Avocat","Défendez vos clients.","0","0","false","false"},{"cuisinier","Cuisinier","Préparez des plats et travaillez en cuisine.","2","0","false","false"},{"psychopathe","Psychopathe","Métier réservé.","2","0","true","false"},{"hackeur","Hackeur","Hackez des systèmes.","2","0","true","false"},{"livreur","Livreur","Livrez des colis.","0","0","false","false"},{"vigile","Vigile","Surveillez et sécurisez.","0","0","false","false"},{"pompier","Pompier / SAMU","Métier sur candidature.","0","0","false","true"},{"banquier","Banquier","Métier sur candidature.","0","0","false","true"},{"agentimmo","Agent immobilier","Métier sur candidature.","0","0","false","true"},{"police","Police","Métier sur candidature.","0","0","false","true"}};for(String[]d:a){Job j=new Job();j.id=d[0];j.name=d[1];j.description=d[2];j.max=Integer.parseInt(d[3]);j.salary=Integer.parseInt(d[4]);j.premium=Boolean.parseBoolean(d[5]);j.candidature=Boolean.parseBoolean(d[6]);JOBS.add(j);}}
 private static void writeDefault(Path p)throws IOException{defaults();List<String>o=new ArrayList<>();o.add("# MineNorth Systeme - France Travail");o.add("# Ajoutez/supprimez des blocs [[jobs]], puis utilisez /emploireload.");o.add("");o.add("[general]");o.add("enabled = true");o.add("default_job = \"civil\"");o.add("assign_command = \"\"");o.add("premium_permission = \"premium.job\"");o.add("");o.add("[salary]");o.add("enabled = false");o.add("interval_minutes = 40");o.add("# Exemple : money give {player} {salary}");o.add("command = \"\"");for(Job j:JOBS){o.add("");o.add("[[jobs]]");o.add("id = \""+j.id+"\"");o.add("name = \""+j.name+"\"");o.add("description = \""+j.description.replace("\"","\\\"")+"\"");o.add("max = "+j.max);o.add("salary = "+j.salary);o.add("premium = "+j.premium);o.add("candidature = "+j.candidature);o.add("permission = \"\"");o.add("icon = \"minecraft:paper\"");o.add("select_command = \"\"");o.add("leave_command = \"\"");o.add("clear_inventory_on_select = false");o.add("clear_inventory_on_leave = false");}Files.write(p,o,StandardCharsets.UTF_8);}
 public static List<Job> jobs(){return Collections.unmodifiableList(JOBS);} public static Job byId(String id){return JOBS.stream().filter(j->j.id.equalsIgnoreCase(id)).findFirst().orElse(null);} public static boolean enabled(){return enabled;} public static boolean salaryEnabled(){return salaryEnabled&&!salaryCommand.isBlank();} public static int intervalMinutes(){return interval;} public static String salaryCommand(){return salaryCommand;} public static String assignCommand(){return assignCommand;} public static String defaultJob(){return defaultJob;} public static String premiumPermission(){return premiumPermission;}
}
